#!/bin/sh

function trailing_whitespace {
  if git rev-parse --verify HEAD >/dev/null 2>&1
  then
    against=HEAD
  else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
  fi

  exec git diff-index --check --cached $against
}

echo "Executing git pre-comit hook..."

trailing_whitespace

echo "done"
