[colors]
ansi = [
  "#121212",
  "#821A1A",
  "#569F7A",
  "#8E700B",
  "#696E9B",
  "#EA0BA4",
  "#D0D0D0",
  "#B0B0B0",
]
brights = [
  "#49483E",
  "#821A1A",
  "#569F7A",
  "#8E700B",
  "#696E9B",
  "#EA0BA4",
  "#D0D0D0",
  "#B0B0B0",
]
cursor_bg = "#D0D0D0"
cursor_border = "#D0D0D0"
cursor_fg = "#121212"
foreground = "#B0B0B0"
background = "#121212"

[metadata]
aliases = ["Fog Dark"]
name = "Fog Dark"
